### ISSUE TITLE
Fix the javascript/windows build

### ISSUE THREAD

**Issue by mattwynne** [cucumber/gherkin-utils#2]
### 🤔 What's the problem you've observed?

Javascript tests fail on Windows

e.g. https://github.com/cucumber/gherkin-utils/actions/runs/3504533429/jobs/5870269520

### ✨ Do you have a proposal for making it better?

Figure it out and fix it.

### 📚 Any additional context?

Breaking this out of scope of #1

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/developer_experience.md)*

**Comment by jennek** [comment]
The problem seems to be here

```ts
  const tckMessageFiles = fg.sync(
    `${__dirname}/../node_modules/@cucumber/compatibility-kit/features/**/*.ndjson`
  )
```

`fastglob` requires POSIX style patterns, in particular forward slashes. `__dirname` contains a Windows style path with backward slashes. source: https://github.com/mrmlnc/fast-glob#how-to-write-patterns-on-windows
Replacing `__dirname` with `__dirname.replace(/\\/g, '/')` solved it for me. Using `unixify` would be the more elegant solution.

**Comment by jennek** [comment]
there is a similar issue here
https://github.com/cucumber/gherkin-utils/blob/main/javascript/test/prettyTest.ts#:~:text=const%20featureFiles%20%3D%20fg.sync(%60%24%7B__dirname%7D/../../../gherkin/testdata/good/*.feature%60)

as no files are found by `fg.sync`, no tests are run.
